### ISSUE TITLE
FiOne Decompiler

### ISSUE THREAD

**Issue by Arkinetic** [Rerumu/FiOne#11]
Hello, so i'm trying to create a Text Editor like Visual Studio Code. I have a button with the code of: 
script.Parent.MouseButton1Click:Connect(function()
	local loadstring = require(workspace.Loadstring)
	local executable, compileFailReason = loadstring(script.Parent.Parent.texteditor_.Text)
	executable()
	end)  -- this button is a run button to run the code in the texteditortextbox*
and i also have an output textbox
but i dont really know how to make the thing say in the output textbox
instead of the normal roblox studio console.
Help would be really appreciated!

**Comment by arkinetic** [comment]
![Screenshot_43](https://user-images.githubusercontent.com/86156119/171732756-52e15b38-a587-45b3-990b-e3004e17f1e4.png)

**Comment by ghost** [comment]
You'll have to provide replacements for built ins like `print` to the FiOne environment table. It looks like its usage is proxied in the example code so you should reach out to the distributor of the set of modules you're using.

**Comment by arkinetic** [comment]
@Rerumu Could you maybe explain more with a screenshot or a video on how to do it? I'm not really a scripter.

**Comment by reversed-coffee** [comment]
@DanPlayz23 You can create a table to specify an environment, which holds the global variables for the function. The second argument of `wrap_state` can take an environment table. For example, `wrap_state(state, { print = warn })()` will call the state and inside of it, `print` would be the same as `warn`, so `print("Hello, world!")` would be `warn("Hello, world!")` instead. The problem here is that you won't have other globals like `Color3`, so what you can do is set the `__index` metamethod value to `getfenv()` which will fallback to the script's environment. With that little bit of metatable magic, you can pass a custom environment table to replace functions like `print` with your own print function that appends to your custom output.
