### ISSUE TITLE
implement fenv support

### ISSUE THREAD

**Issue by plac3** [Rerumu/FiOne#7]
I myself, know as much of Lua bytecode as I know about socialising, so I won't make a PR or anything. Currently upon usage of setfenv using the function returned by FiOne results in an error. For source this is the module I'm using https://www.roblox.com/library/4689019964/vLua-5-1-improved-VM
![image](https://user-images.githubusercontent.com/84245312/120494713-6d389b80-c392-11eb-94aa-37ac1b813bc7.png)
![image](https://user-images.githubusercontent.com/84245312/120494770-79245d80-c392-11eb-8491-09551d371289.png)
last screenshot is unorganized because i was using setfenv(0,custom_env) as a bandaid fix

**Comment by reversed-coffee** [comment]
It seems like your issue here is that you are trying to access a global that doesn't exist. The environment holds **all** global functions and global variables, so everything on the older function environment (like print, workspace, game, etc.) would not exist. Here's an example of what's happening:
```lua
local function F()
    print(_VERSION) --> Should be Lua 5.1, but it is nil because it doesn't exist in the environment.
end

setfenv(F, {
    print = print
})
F()
```
To counteract this, add the globals that you need to the environment.

**Comment by plac3** [comment]
> It seems like your issue here is that you are trying to access a global that doesn't exist. The environment holds **all** global functions and global variables, so everything on the older function environment (like print, workspace, game, etc.) would not exist. Here's an example of what's happening:
> 
> ```lua
> local function F()
>     print(_VERSION) --> Should be Lua 5.1, but it is nil because it doesn't exist in the environment.
> end
> 
> setfenv(F, {
>     print = print
> })
> F()
> ```
> 
> To counteract this, add the globals that you need to the environment.

I don't believe that's what's happening but I should've attached full script, that is my bad.
Here it is:
```lua
local loadstring = require(script.Loadstring)
local Runner = script.Runner
local Request = script.Request
local Players = game:GetService("Players")

local normal_env = getfenv(0)
local custom_env = setmetatable({}, { __index=function(_,Function)
	return normal_env[Function]
end})

custom_env["NLS"] = function(Code, Parent)
	return Request:Invoke("NLS", Code, Parent)
end
custom_env["NS"] = function(Code, Parent)
	return Request:Invoke("NS", Code, Parent)
end

Runner.Event:Connect(function(Code, Runner)
	custom_env["owner"] = Runner
	
	if Code then
		custom_env["loadstring"] = function(code)
			local s,e = loadstring(code, custom_env)
			
			return s,e
		end
		setfenv(0, custom_env)
		local s,e = loadstring(Code, custom_env)
		if not s then
			error(debug.traceback(e))
		else
			s()
		end
	end
end)
```

**Comment by Reinitialized** [comment]
FiOne is an interpreter, not a full blown VM like [LuLu](http://lulu.luaforge.net/), meaning it relies entirely on the host Lua environment vs implementing it's own. Implementing fenv support wouldn't be possible let alone necessary. Clearly something else is going on here which I strongly believe to be an error with how FiOne is interpreting Lua 5.1 bytecode. Due to my lack of understanding of how Lua bytecode works, I have no idea what specifically, however I do know there's been more than a few edge cases in which errors like this pop up from other users of vLua.

**Comment by ghost** [comment]
What exactly is the `loadstring` function doing? The overall code looks fine so I suspect the issue might be in how the env is being passed into FiOne.

**Comment by Reinitialized** [comment]
> What exactly is the `loadstring` function doing? The overall code looks fine so I suspect the issue might be in how the env is being passed into FiOne.

essentially, it's:
```Lua
return setfenv(fione(compiledBytecode), env)
```

**Comment by ghost** [comment]
Then it might be an issue of the wrapper, not FiOne. `wrap_lua_func` takes the environment as its second argument, so `setfenv` is not required at all.

**Comment by plac3** [comment]
The issue was the wrapper, upon usage of the second argument in wrap_lua_func it worked.

**Comment by Reinitialized** [comment]
I pushed out an update to vLua to resolve this, apologies for the trouble.
